# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [9]:
import numpy as np

nombre = "Yesenia"
edad = 30

print(f"Hola, me llamo {nombre} y tengo {edad} años")




Hola, me llamo Yesenia y tengo 30 años


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [ ]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí

# Imprimimos el primer elemento (posición 0) y el último (posición -1)
print("Primer elemento:", numeros[0])
print("Ultimo elemento:", numeros[-1])

# Usamos 'slicing' para sacar los tres primeros (del índice 0 al 3, sin incluir el 3)
tres_primeros = numeros[0:3]
print("Los tres primeros son:", tres_primeros)

# Usamos la función append para poner el 99 al final de la lista
numeros.append(99)

# Imprimimos la lista completa para verificar que se agregó el 99
print("Lista actualizada:", numeros)


Primer elemento: 10
Último elemento: 15
Los tres primeros son: [10, 25, 3]
Lista actualizada: [10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [2]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
# Extraemos el promedio del diccionario para compararlo
nota = estudiante["promedio"]

# Estructura de decisión: si la nota es 6 o más, imprime Aprobado
if nota >= 6:
    print("Aprobado")
else:
    # Si la condición de arriba no se cumple, imprime Reprobado
    print("Reprobado")


Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [ ]:
# Tu respuesta aquí
# Definimos la función para calcular el área
def calcular_area(base, altura):
    # Realizamos la operación matemática y la guardamos en una variable
    area = (base * altura) / 2
    # 'return' sirve para que la función nos devuelva el resultado final
    return area

# Llamamos a la función con los valores que nos pidió el ejercicio
resultado = calcular_area(5, 8)

# Imprimimos el resultado final usando un f-string para que se vea claro
print(f"El área del triangulo es: {resultado}")

El area del triangulo es: 20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [4]:
# Tu respuesta aquí
# Usamos range(1, 11) para generar los números del 1 al 10 (el 11 no se incluye)
cuadrados = [numero ** 2 for numero in range(1, 11)]

# Imprimimos la lista final
print("Los cuadrados del 1 al 10 son:", cuadrados)

Los cuadrados del 1 al 10 son: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [8]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [9]:
# Tu respuesta aquí
# --- 1. Arreglo con valores decimales ---
arreglo_decimal = np.array([1.5, 2.5, 3.5, 4.5])
print("1. Arreglo decimal:", arreglo_decimal)
print("   Shape:", arreglo_decimal.shape)  # Nos dice el tamaño
print("   Dtype:", arreglo_decimal.dtype)  # Nos dice el tipo de dato
print("-" * 30)

# --- 2. Matriz de ceros de 3x4 ---
matriz_ceros = np.zeros((3, 4))
print("2. Matriz de ceros:\n", matriz_ceros) # \n es para que imprima en una línea nueva y se vea bonito
print("   Shape:", matriz_ceros.shape)
print("   Dtype:", matriz_ceros.dtype)
print("-" * 30)

# --- 3. Valores espaciados con linspace ---
arreglo_espaciado = np.linspace(0, 1, 6)
print("3. Arreglo linspace:", arreglo_espaciado)
print("   Shape:", arreglo_espaciado.shape)
print("   Dtype:", arreglo_espaciado.dtype)


1. Arreglo decimal: [1.5 2.5 3.5 4.5]
   Shape: (4,)
   Dtype: float64
------------------------------
2. Matriz de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
   Shape: (3, 4)
   Dtype: float64
------------------------------
3. Arreglo linspace: [0.  0.2 0.4 0.6 0.8 1. ]
   Shape: (6,)
   Dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [10]:
a = np.arange(1, 13)

# Tu respuesta aquí

# 1. Usamos reshape para cambiar la forma a 3 filas y 4 columnas
matriz = a.reshape(3, 4)

# 2. Encontramos los valores pedidos usando las herramientas de NumPy
valor_maximo = matriz.max()
valor_minimo = matriz.min()

# argmax nos da la posición (el índice) donde está guardado el valor máximo
posicion_maximo = matriz.argmax()

# Imprimimos los resultados para ver cómo quedó
print("La matriz de 3x4 quedó así:\n", matriz)
print("-" * 30)
print("El valor más grande es:", valor_maximo)
print("El valor más pequeño es:", valor_minimo)
print("La posición del valor máximo es:", posicion_maximo)


La matriz de 3x4 quedó así:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------------------------
El valor más grande es: 12
El valor más pequeño es: 1
La posición del valor máximo es: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [11]:
# Tu respuesta aquí
# Se crean dos arreglos con 5 números aleatorios cada uno.
arreglo_A = np.random.randint(1, 21, size=5)
arreglo_B = np.random.randint(1, 21, size=5)

print("Arreglo A:", arreglo_A)
print("Arreglo B:", arreglo_B)
print("-" * 30)

# 1. Suma
suma = arreglo_A + arreglo_B
print("El resultado de la suma es:", suma)

# 2. Resta
resta = arreglo_A - arreglo_B
print("El resultado de la resta es:", resta)

# 3. Multiplicación
multiplicacion = arreglo_A * arreglo_B
print("El resultado de la multiplicación es:", multiplicacion)


Arreglo A: [20  4 11  7 15]
Arreglo B: [18 12 10 13 19]
------------------------------
El resultado de la suma es: [38 16 21 20 34]
El resultado de la resta es: [ 2 -8  1 -6 -4]
El resultado de la multiplicación es: [360  48 110  91 285]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [14]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
notas_aprobadas = notas[notas >= 6]

# Imprimimos el resultado final
print("Notas originales:", notas)
print("Notas mayores o iguales a 6", notas_aprobadas)


Notas originales: [ 8.5  6.   9.2  4.3  7.8  5.5 10.   3.1]
Notas mayores o iguales a 6 [ 8.5  6.   9.2  7.8 10. ]
